


# SPRING_DATASOURCE_URL="jdbc:mysql://mysql.railway.internal:3306/railway?useTimezone=true&serverTimezone=America/Sao_Paulo&autoReconnect=true&useSSL=false"
# SPRING_DATASOURCE_USERNAME="root"
# SPRING_DATASOURCE_PASSWORD="zkmPWocIAzAJRrrKStWVTEDshYKFmqkL"


# MYSQL
spring.datasource.url= jdbc:mysql://localhost:3306/lactalis5pq?useTimezone=true&serverTimezone=America/Sao_Paulo&useSSL=false
spring.datasource.username=root
spring.datasource.password=

server.forward-headers-strategy=framework
server.port=8080

server.servlet.session.timeout=30m
server.servlet.session.cookie.name=APPMAINSESSION

#JPA
spring.jpa.hibernate.ddl-auto= update
# spring.jpa.show-sql= true
# spring.jpa.open-in-view= true

# THYMELEAF
spring.thymeleaf.cache= false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#VPS
app.upload.dir=/opt/uploads
server.use-forward-headers=true


# # # Formata as instruções SQL para melhor leitura
# spring.jpa.properties.hibernate.format_sql=true

# # Mostra os valores dos parâmetros nas instruções SQL
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql=TRACE

# logging.level.org.springframework.security=DEBUG



